version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - reservas-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  api-gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - RESERVAS_URL=http://reservas:3001
      - INVENTARIO_URL=http://inventario:3002
      - PAGOS_URL=http://pagos:3003
      - NOTIFICACIONES_URL=http://notificaciones:3004
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - reservas-net

  reservas:
    build:
      context: .
      dockerfile: services/reservas/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - REDIS_URL=redis://redis:6379
      - INVENTARIO_URL=http://inventario:3002
      - PAGOS_URL=http://pagos:3003
      - NOTIFICACIONES_URL=http://notificaciones:3004
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - reservas-net

  inventario:
    build:
      context: .
      dockerfile: services/inventario/Dockerfile
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - REDIS_URL=redis://redis:6379
      - SIMULAR_FALLO=false
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - reservas-net

  pagos:
    build:
      context: .
      dockerfile: services/pagos/Dockerfile
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - SIMULAR_LATENCIA=false
      - LATENCIA_MS=20000
    networks:
      - reservas-net

  notificaciones:
    build:
      context: .
      dockerfile: services/notificaciones/Dockerfile
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
    networks:
      - reservas-net

networks:
  reservas-net:
    driver: bridge
